mappings:
  FrontEndGridField: WebbuildersGroup\FrontendGridField\Forms\GridField\FrontEndGridField
  FrontEndGridFieldConfig_Base: WebbuildersGroup\FrontendGridField\Forms\GridField\FrontEndGridFieldConfig_Base
  FrontEndGridFieldConfig_RecordViewer: WebbuildersGroup\FrontendGridField\Forms\GridField\FrontEndGridFieldConfig_RecordViewer
  FrontEndGridFieldConfig_RecordEditor: WebbuildersGroup\FrontendGridField\Forms\GridField\FrontEndGridFieldConfig_RecordEditor
  FrontEndGridFieldConfig_RelationEditor: WebbuildersGroup\FrontendGridField\Forms\GridField\FrontEndGridFieldConfig_RelationEditor
  FrontEndGridFieldDetailForm: WebbuildersGroup\FrontendGridField\Forms\GridField\FrontEndGridFieldDetailForm
  FrontEndGridFieldDetailForm_ItemRequest: WebbuildersGroup\FrontendGridField\Forms\GridField\FrontEndGridFieldDetailForm_ItemRequest
