mappings:
  FrontEndGridField: WebbuildersGroup\FrontEndGridField\Forms\GridField\GridField
  FrontEndGridFieldConfig_Base: WebbuildersGroup\FrontEndGridField\Forms\GridField\GridFieldConfig_Base
  FrontEndGridFieldConfig_RecordViewer: WebbuildersGroup\FrontEndGridField\Forms\GridField\GridFieldConfig_RecordViewer
  FrontEndGridFieldConfig_RecordEditor: WebbuildersGroup\FrontEndGridField\Forms\GridField\GridFieldConfig_RecordEditor
  FrontEndGridFieldConfig_RelationEditor: WebbuildersGroup\FrontEndGridField\Forms\GridField\GridFieldConfig_RelationEditor
  FrontEndGridFieldDetailForm: WebbuildersGroup\FrontEndGridField\Forms\GridField\GridFieldDetailForm
  FrontEndGridFieldDetailForm_ItemRequest: WebbuildersGroup\FrontEndGridField\Forms\GridField\GridFieldDetailForm_ItemRequest
